using System;
using System.Collections.Generic;

namespace Assets.Code.Domain.Map
{
    // Represents the path through the map


    public class FixedPathGenerator : IPathGenerator
    {
        public Path GeneratePath(MapCoordinate startingPoint, MapCoordinate endingPoint, int mapWidth, int mapHeight)
        {
            return new Path(_MapCoordinates);
        }

        private readonly HashSet<MapCoordinate> _MapCoordinates = new HashSet<MapCoordinate>()
        {
            new MapCoordinate(0, 19),
            new MapCoordinate(1, 19),
            new MapCoordinate(1, 18),
            new MapCoordinate(1, 17),
            new MapCoordinate(2, 17),
            new MapCoordinate(3, 17),
            new MapCoordinate(3, 18),
            new MapCoordinate(4, 18),
            new MapCoordinate(5, 18),
            new MapCoordinate(6, 18),
            new MapCoordinate(7, 18),
            new MapCoordinate(7, 17),
            new MapCoordinate(8, 17),
            new MapCoordinate(9, 17),
            new MapCoordinate(9, 16),
            new MapCoordinate(9, 15),
            new MapCoordinate(10, 15),
            new MapCoordinate(11, 15),
            new MapCoordinate(11, 16),
            new MapCoordinate(11, 17),
            new MapCoordinate(11, 18),
            new MapCoordinate(12, 18),
            new MapCoordinate(13, 18),
            new MapCoordinate(14, 18),
            new MapCoordinate(15, 18),
            new MapCoordinate(16, 18),
            new MapCoordinate(17, 18),
            new MapCoordinate(18, 18),
            new MapCoordinate(18, 17),
            new MapCoordinate(18, 16),
            new MapCoordinate(18, 15),
            new MapCoordinate(18, 14),
            new MapCoordinate(17, 14),
            new MapCoordinate(16, 14),
            new MapCoordinate(16, 15),
            new MapCoordinate(16, 16),
            new MapCoordinate(15, 16),
            new MapCoordinate(14, 16),
            new MapCoordinate(13, 16),
            new MapCoordinate(13, 15),
            new MapCoordinate(13, 14),
            new MapCoordinate(13, 13),
            new MapCoordinate(13, 12),
            new MapCoordinate(12, 12),
            new MapCoordinate(11, 12),
            new MapCoordinate(10, 12),
            new MapCoordinate(9, 12),
            new MapCoordinate(8, 12),
            new MapCoordinate(7, 12),
            new MapCoordinate(7, 13),
            new MapCoordinate(7, 14),
            new MapCoordinate(7, 15),
            new MapCoordinate(6, 15),
            new MapCoordinate(5, 15),
            new MapCoordinate(4, 15),
            new MapCoordinate(3, 15),
            new MapCoordinate(2, 15),
            new MapCoordinate(1, 15),
            new MapCoordinate(1, 14),
            new MapCoordinate(1, 13),
            new MapCoordinate(1, 12),
            new MapCoordinate(1, 11),
            new MapCoordinate(1, 10),
            new MapCoordinate(2, 10),
            new MapCoordinate(3, 10),
            new MapCoordinate(3, 11),
            new MapCoordinate(3, 12),
            new MapCoordinate(3, 13),
            new MapCoordinate(4, 13),
            new MapCoordinate(5, 13),
            new MapCoordinate(5, 12),
            new MapCoordinate(5, 11),
            new MapCoordinate(5, 10),
            new MapCoordinate(6, 10),
            new MapCoordinate(7, 10),
            new MapCoordinate(8, 10),
            new MapCoordinate(8, 9),
            new MapCoordinate(8, 8),
            new MapCoordinate(8, 7),
            new MapCoordinate(8, 6),
            new MapCoordinate(8, 5),
            new MapCoordinate(9, 5),
            new MapCoordinate(10, 5),
            new MapCoordinate(10, 6),
            new MapCoordinate(10, 7),
            new MapCoordinate(10, 8),
            new MapCoordinate(10, 9),
            new MapCoordinate(10, 10),
            new MapCoordinate(11, 10),
            new MapCoordinate(12, 10),
            new MapCoordinate(13, 10),
            new MapCoordinate(14, 10),
            new MapCoordinate(15, 10),
            new MapCoordinate(15, 11),
            new MapCoordinate(15, 12),
            new MapCoordinate(16, 12),
            new MapCoordinate(17, 12),
            new MapCoordinate(18, 12),
            new MapCoordinate(18, 11),
            new MapCoordinate(18, 10),
            new MapCoordinate(18, 9),
            new MapCoordinate(18, 8),
            new MapCoordinate(18, 7),
            new MapCoordinate(18, 6),
            new MapCoordinate(18, 5),
            new MapCoordinate(18, 4),
            new MapCoordinate(18, 3),
            new MapCoordinate(18, 2),
            new MapCoordinate(18, 1),
            new MapCoordinate(17, 1),
            new MapCoordinate(16, 1),
            new MapCoordinate(15, 1),
            new MapCoordinate(14, 1),
            new MapCoordinate(14, 2),
            new MapCoordinate(14, 3),
            new MapCoordinate(15, 3),
            new MapCoordinate(16, 3),
            new MapCoordinate(16, 4),
            new MapCoordinate(16, 5),
            new MapCoordinate(16, 6),
            new MapCoordinate(16, 7),
            new MapCoordinate(16, 8),
            new MapCoordinate(15, 8),
            new MapCoordinate(14, 8),
            new MapCoordinate(13, 8),
            new MapCoordinate(12, 8),
            new MapCoordinate(12, 7),
            new MapCoordinate(12, 6),
            new MapCoordinate(12, 5),
            new MapCoordinate(12, 4),
            new MapCoordinate(12, 3),
            new MapCoordinate(12, 2),
            new MapCoordinate(12, 1),
            new MapCoordinate(11, 1),
            new MapCoordinate(10, 1),
            new MapCoordinate(10, 2),
            new MapCoordinate(10, 3),
            new MapCoordinate(9, 3),
            new MapCoordinate(8, 3),
            new MapCoordinate(8, 2),
            new MapCoordinate(8, 1),
            new MapCoordinate(7, 1),
            new MapCoordinate(6, 1),
            new MapCoordinate(6, 2),
            new MapCoordinate(6, 3),
            new MapCoordinate(6, 2),
            new MapCoordinate(6, 1),
            new MapCoordinate(6, 2),
            new MapCoordinate(6, 3),
            new MapCoordinate(6, 4),
            new MapCoordinate(6, 5),
            new MapCoordinate(6, 6),
            new MapCoordinate(6, 7),
            new MapCoordinate(6, 8),
            new MapCoordinate(5, 8),
            new MapCoordinate(4, 8),
            new MapCoordinate(3, 8),
            new MapCoordinate(2, 8),
            new MapCoordinate(1, 8),
            new MapCoordinate(1, 7),
            new MapCoordinate(1, 6),
            new MapCoordinate(2, 6),
            new MapCoordinate(3, 6),
            new MapCoordinate(4, 6),
            new MapCoordinate(4, 5),
            new MapCoordinate(4, 4),
            new MapCoordinate(3, 4),
            new MapCoordinate(2, 4),
            new MapCoordinate(1, 4),
            new MapCoordinate(1, 3),
            new MapCoordinate(1, 2),
            new MapCoordinate(2, 2),
            new MapCoordinate(3, 2),
            new MapCoordinate(4, 2),
            new MapCoordinate(4, 1),
            new MapCoordinate(4, 0),
            new MapCoordinate(3, 0),
            new MapCoordinate(2, 0),
            new MapCoordinate(1, 0),
            new MapCoordinate(0, 0),
        };

    }
}